### ISSUE TITLE
Hot-reloading blocking CSS reload

### ISSUE THREAD

**Issue by gbj** [leptos-rs/cargo-leptos#108]
It seems that something in my hot-reloading PR is blocking the style change notification at some point.

I'm assigning this to myself but it will probably a couple weeks before I'm able to take a look so feel free if you have an idea.

## Steps to Reproduce
1. Install latest `cargo-leptos` from git
2. Open Tailwind example in the Leptos repo
3. `cargo leptos watch -v --hot-reload`
4. Edit any class

## Behavior
The class is updated in the DOM, but the CSS file is not reloaded, so it's as if the class has actually disappeared.

`cargo-leptos` logs:
```
      Notify lib source change write "src/app.rs"
      Notify bin source change write "src/app.rs"
      Assets finished (no changes)
       Style no build needed ChangeSet([LibSource, BinSource])
    Patching view.
      Reload server port 127.0.0.1:3000 open
      Reload sent "reload all" to browser
    Blocking waiting for file lock on package cache
      Notify style change write "style/output.css"
       Build interrupted. Restarting.
       Watch waiting for changes
      Assets finished (no changes)
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache

[etc.]

      Reload server port 127.0.0.1:3000 open
      Reload sent "reload all" to browser
```

The new CSS doesn't appear until the reload is set. i.e., Tailwind is updating the CSS file but `cargo-leptos` isn't sending a reload single for the CSS file.

**Comment by d4h0** [comment]
@gbj: With `Tailwind example` you mean [this one](https://github.com/leptos-rs/leptos/tree/main/examples/tailwind), right?

Is this example supposed to use the new Tailwind integration of `cargo-leptos`?

If so, this isn't set up properly.

I was trying to figure out what the issue is here, and was wondering why none of my Tailwind classes were generated – even when I removed the `--hot-reload` flag. Somehow only the initial Tailwind classes, which were defined in the source code on GitHub, worked.

When I opened `Cargo.toml`, I noticed that it doesn't contain the required option to activate Tailwind support.

Besides that, the example includes [`style/output.css`](https://github.com/leptos-rs/leptos/blob/main/examples/tailwind/style/output.css), which is a CSS file that Tailwind has generated.

So basically, to fix the issue, you can do the following:

(1) Delete `style/output.css` (this will automatically be generated and included by `cargo leptos`)

(2) Apply the following changes to `Cargo.toml`

```
# style-file = "style/output.css" # Or remove completely
tailwind-input-file = "./input.css"
```

After that, Tailwind works properly. At least, without the `--hot-reload` flag.

---

With `--hot-reload`, the CSS classes on HTML elements update immediately, but the new stylesheet isn't generated immediately, so the classes don't have any CSS associated with them (i.e. the element is displayed without the intended style).

At the moment, `--hot-reload` and the regular `cargo leptos` build mode seem to run at the same time. When that regular build process is finished, the newly generated stylesheet is sent to the browser, which takes 3-6 seconds on my machine.

My guess is, in the end, `--hot-reload` will suppress the regular build process, when it detects changes that it can handle.

---

The next problem then will be, that Tailwind isn't executed anymore.

At the moment, Tailwind is only executed when `cargo leptos`' file watcher detects changes (i.e. Tailwind's own file watcher doesn't run). See [this comment](https://github.com/leptos-rs/cargo-leptos/issues/18#issuecomment-1406095329), or [the src](https://github.com/leptos-rs/cargo-leptos/blob/7e993f5262da8efacb28bc347dd38563ee7d7753/src/compile/tailwind.rs#L71).

Triggering the execution of Tailwind from the code that is executed via `--hot-reload` is most-likely not difficult.

However, a full Tailwind build can be pretty slow. I have only the DaisyUI Tailwind plugin installed, and a full build takes already 2.2 seconds (as mentioned above, a regular (incremental) build with `cargo leptos` take 3-6 seconds on my machine).

Therefore, I think, `cargo leptos` would need to have an option to use Tailwind's file system watcher, to reap the full potential of `--hot-reload`.

With Tailwind's file system watcher an (incremental) update takes only 30ms.

**Comment by d4h0** [comment]
> Is this example supposed to use the new Tailwind integration of `cargo-leptos`?

Oops, I should have read the [README of the example](https://github.com/leptos-rs/leptos/blob/main/examples/tailwind/README.md). The example doesn't use the new Tailwind integration of `cargo-leptos`.

So `Steps to Reproduce` above is missing `npx tailwindcss -i ./input.css -o ./style/output.css --watch`.

I switched from the build in Tailwind integration to a setup similar to what the example does, and now everything seems to work. When I change a class, and switch to my browser, the page is already updated, which is pretty amazing :)

The things I wrote about the build in Tailwind integration in my last comment are still true. Without using Tailwind's own file watcher, the page updates will not be instantaneous.

**Comment by gbj** [comment]
> Oops, I should have read the [README of the example](https://github.com/leptos-rs/leptos/blob/main/examples/tailwind/README.md). The example doesn't use the new Tailwind integration of `cargo-leptos`.
> 
> So `Steps to Reproduce` above is missing `npx tailwindcss -i ./input.css -o ./style/output.css --watch`.

All correct.

> I switched from the build in Tailwind integration to a setup similar to what the example does, and now everything seems to work. When I change a class, and switch to my browser, the page is already updated, which is pretty amazing :)

Me too, but only if I'm changing to a class that's already been used. I'm not sure exactly how Tailwind purges things or doesn't, but it appears it keeps some classes around that have been used previously and then removed. So for example if I switch `text-center` to `text-left` it updates instantaneously, because `text-left` is already in the CSS file for me (?) But if I switch to `bg-blue-300` or something, it doesn't exist until full page reload because the CSS reload signal is not being sent. If I then switch back to whatever background class it was before, it again works instantaneously because the class is already there in the CSS. 

This part is the behavior I'm hoping to fix, I just haven't had a lot of time to look at it in the last couple weeks.

> The things I wrote about the build in Tailwind integration in my last comment are still true. Without using Tailwind's own file watcher, the page updates will not be instantaneous.

This part is also true.

**Comment by gbj** [comment]
I think this is actually fairly straightforward, although I have pretty limited experience with concurrent code so I may be missing something.

https://github.com/leptos-rs/cargo-leptos/blob/1559411fd70ad7096eb304a46956c675b4fd2d81/src/command/watch.rs#L62-L68

Basically whenever we get a "some files changed" interrupt, we run everything.

If it's *just* a CSS file, it will only update the CSS, and there will be no lib/bin rebuild, so this will resolve pretty much immediately (or when the SASS/Tailwind processes are finished).

But if it's Tailwind and is editing something in the Rust source files, lib/bin/style all need to be rebuilt. Because of the `join` here, we wait for all of them to finish rebuilding.

If, instead, I split the style out into a separate process, it sends the update when the incremental build is complete. I've tested this with the Tailwind CLI but should work with the Tailwind integration too.

Here's my branch: https://github.com/gbj/cargo-leptos/blob/ec5d1c4b99a733feae4a775e9a17e811448ebf72/src/command/watch.rs#L62-L78

But this only works *once* (i.e., only for the first style change made within a certain rebuild run), I think because the build process isn't interrupted again if you save the file again during the rebuild process?

Anyway I'll make a draft PR with this.

**Comment by d4h0** [comment]
> I just haven't had a lot of time to look at it in the last couple weeks.

@gbj, please don't feel any pressure to respond to any of my comments, unless you have enough time, and you feel like it.

> Me too, but only if I'm changing to a class that's already been used. I'm not sure exactly how Tailwind purges things or doesn't, but it appears it keeps some classes around that have been used previously and then removed.

Damn, you are right! I didn't realize that Tailwind keeps previously seen classes in watch mode... 🙈

After thinking about it, this makes sense. Otherwise, Tailwind would have to keep track, where classes are found.

Sorry for the noise... 🙈
