### ISSUE TITLE
Warning about rust 2021 and project workspace resolver

### ISSUE THREAD

**Issue by aperepel** [leptos-rs/cargo-leptos#170]
Review and update configs. While running `cargo test --features=full_tests`

```
   Front compiling WASM
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```

**Comment by martinfrances107** [comment]
I can't reproduce this today....I think the issue  should be closed.

This warning and is solution is covered by many migration guidelines 

the solution is to find the root Cargo.toml file and add this "resolver line" to the workspace section 

```
[workspace]
+ resolver = "2"
```
For this project -- one place this could be added is 

examples/workspace/Cargo.toml

But it is not required, I *think*, but am not sure - it is because the project has recently added this line to the root Cargo.toml

# OnceLock was stabailzed in 1.70
rust-version = "1.70"

time moves on.
