### ISSUE TITLE
Favicon not served in new project?

### ISSUE THREAD

**Issue by epigramengineer** [leptos-rs/cargo-leptos#195]
I'm running a new leptos project built with `cargo leptos new --git https://github.com/leptos-rs/start-axum`, but when I run `cargo leptos watch` it doesn't load the favicon on the site. Inspecting in chrome web tools "sources" tab it's not vended, though the pkg directory is.

The contents of the site appear to be built correctly. 
```
❯ tree target/site 
target/site
├── favicon.ico
└── pkg
    ├── example.css
    ├── example.js
    └── example.wasm
```

Any ideas what I'm doing wrong?

**Comment by gbj** [comment]
No idea. If you load `localhost:3000/favicon.ico` (or whatever port you're at), does it serve the favicon? The default starter does server the file from `public/favicon.ico`, so not sure what you changed that stopped that from happening.

**Comment by benwis** [comment]
Closing as stale, please open a new issue if you're still experiencing htis

**Comment by christopherc1331** [comment]
I know this issue is closed... but I had the same problem with the same leptos init and site root directory.

I discovered that it was due to a browser compatibility issue (I was using Brave initially), and switching to Chrome proper resolved. In Brave, the browser wasn't calling the favicon endpoint on page load, but if you called the route manually the icon was fetched/rendered. Chrome does make the call to fetch the favicon, though.
