### ISSUE TITLE
Tailwind is not compiled with dart-sass when file extension is .scss

### ISSUE THREAD

**Issue by mrdev023** [leptos-rs/cargo-leptos#209]
**Is your feature request related to a problem? Please describe.**
Tailwind is not compiled with dart-sass when file extension is .scss
tailwind-input-file = "style/tailwind.scss"

**Describe the solution you'd like**
It run tailwindcss directly

**Describe alternatives you've considered**
Compile with dart-sass and then with tailwindcss

**Comment by crapStone** [comment]
Tailwindcss is called directly (see [here](https://github.com/leptos-rs/cargo-leptos/blob/main/src/compile/tailwind.rs#L81)). Tailwind [discourages the use of preprocessors](https://tailwindcss.com/docs/using-with-preprocessors#using-sass-less-or-stylus), please take a look at their documentation.  
If you come to the conclusion that it is still a bug in `cargo-leptos` please elaborate more, so that we can fix the issue.

**Comment by StringKe** [comment]
You can add the scss compiled file to tailwind.css and then compile tailwindcss.

Separated as two separate processors, the supplied scss would be useless (a lot of css variables would need to be written to match the colors, sizes, and styles in tailwindcss) and the `@layer` `@apply` features provided by tailwindcss would not be available in scss.

**Comment by benwis** [comment]
Closing as this appears to be resolved
