### ISSUE TITLE
Hangs on ctrl-c when building

### ISSUE THREAD

**Issue by akesson** [leptos-rs/cargo-leptos#54]

**Comment by phillipbaird** [comment]
I think I have a fix for this issue.  You can review this in my fork here: https://github.com/phillipbaird/cargo-leptos/commit/dedddb5549346e190366ddd598e396e0cccebf51

The `build_proj` function did not consider the Outcome of each compile stage. This function has been altered so the build is short circuited if a compile is stopped.

Likewise the `build_all` function would build a list of projects without checking for shutdowns. This function has been changed to check after a call to `build_proj` to also short circuit if a shutdown is requested.

build_proj is called from end2end and at the start of a watch.  Both these modules have been changed so that after `build_proj` has been called they check for shutdown requests and exit if required.

@akesson When you have a moment could you please review and let me know if you'd like a pull request for this?
